FROM jupyter/base-notebook:python-3.11

USER root
RUN apt-get update && apt-get install -y openjdk-17-jdk && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Thiết lập biến môi trường Java 17
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH

COPY requirements.txt .

# Cài đặt các thư viện Python cần thiết
RUN pip install --upgrade pip \
    && pip install -r requirements.txt
